async(page)=>{
const checks=[];const check=(v,n)=>{if(!v)throw Error(n);checks.push(n)};
await page.setViewportSize({width:1440,height:900});
let release;const gate=new Promise(r=>release=r);
await page.route('**/api/contacts',async route=>{await gate;await route.continue()});
await page.reload({waitUntil:'domcontentloaded'});
await page.getByRole('status',{name:'Loading contacts'}).waitFor();
check(await page.getByRole('searchbox').isDisabled(),'Loading disables filters');
await page.screenshot({path:'artifacts/verification/b9b12b31e7d01c7ac1fa175b16157b861445e1e2/loading.png'});
release();await page.getByText('6 of 6 contacts').waitFor();await page.unroute('**/api/contacts');
await page.route('**/api/contacts',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Verifier injected unavailable'})}));
await page.reload();await page.getByRole('alert').waitFor();
check((await page.getByRole('alert').innerText()).includes('Contacts could not be loaded'),'Load error banner');
await page.screenshot({path:'artifacts/verification/b9b12b31e7d01c7ac1fa175b16157b861445e1e2/load-error.png'});
await page.unroute('**/api/contacts');await page.getByRole('button',{name:'Retry',exact:true}).click();
await page.getByText('6 of 6 contacts').waitFor();check(true,'Retry recovers real API data');
await page.getByRole('button',{name:/Dev Patel/}).filter({visible:true}).click();
await page.getByLabel('Notes',{exact:true}).fill('Unsaved fictional retry note');
await page.route('**/api/contacts/*',r=>r.request().method()==='PUT'?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Verifier injected save failure'})}):r.continue());
await page.getByRole('button',{name:'Save changes',exact:true}).click();
await page.getByRole('alert').waitFor();
check(await page.getByLabel('Notes',{exact:true}).inputValue()==='Unsaved fictional retry note','Failed save preserves input');
await page.screenshot({path:'artifacts/verification/b9b12b31e7d01c7ac1fa175b16157b861445e1e2/save-error.png'});
await page.unroute('**/api/contacts/*');
await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText(/Saved at/).waitFor();check(true,'Save retry succeeds');
await page.getByRole('button',{name:'Delete',exact:true}).click();
await page.getByRole('alertdialog').getByRole('textbox').fill('Dev Patel');
await page.route('**/api/contacts/*',r=>r.request().method()==='DELETE'?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Verifier injected delete failure'})}):r.continue());
await page.getByRole('button',{name:'Delete contact',exact:true}).click();await page.getByRole('alert').waitFor();
check(await page.getByRole('alertdialog').isVisible(),'Failed delete preserves dialog and contact');
await page.screenshot({path:'artifacts/verification/b9b12b31e7d01c7ac1fa175b16157b861445e1e2/delete-error.png'});
await page.unroute('**/api/contacts/*');await page.getByRole('alertdialog').getByRole('button',{name:'Cancel'}).click();
await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.route('**/api/contacts',r=>r.fulfill({status:200,contentType:'application/json',body:'{"contacts":[]}'}));
await page.reload();await page.getByRole('heading',{name:'No contacts yet'}).waitFor();check(true,'Empty database UI and create action');
await page.screenshot({path:'artifacts/verification/b9b12b31e7d01c7ac1fa175b16157b861445e1e2/empty.png'});
await page.unroute('**/api/contacts');await page.reload();await page.getByText('6 of 6 contacts').waitFor();
return checks;
}
